export const OPEN_EDIT_PAGE = 'OPEN_EDIT_PAGE';

export const ADD_CALENDAR_DATA_ITEM = 'ADD_CALENDAR_DATA_ITEM';

export const SET_CURRENT_CALENDAR_DATA_ITEM = 'SET_CURRENT_CALENDAR_DATA_ITEM';

export const CLEAR_CURRENT_CALENDAR_DATA_ITEM = 'CLEAR_CURRENT_CALENDAR_DATA_ITEM';
